/*
 * Sepcifications
 */
package org.ifeth.sehr.p1507291734.lib;

/**
 * This is a global definition file of commonly used constants and default
 * system settings.
 *
 * @author hansjhaase
 */
public class Constants {

  //============================================= Common SEHR definitions
  //Internal Projekt Management Number (by IFETH and MDI), 'AppToken'
  public static final String MODULE_PIK = "p1507291734";
  //Globally unique identifier generated by GenSEHRGUID on project setup!
  public static final String MODULE_GUID = "465FFC55-1458-4767-B6CD-DA3B4EAB6426";
  public static final String MODULE_CFG_FILE = "";
  //customer/distrib main version - minor see maven/SVN/GIT 
  public static final String MODULE_VERSION = "0.2";
  //see JMed/SEHR project doc, also used as 'AppName'
  public static final String MODULE_NAME = "SEHRAdminTool";
  
  //module definitions
  public static final String ICPropName = "sehr/" + Constants.MODULE_PIK + "/Properties";
}
